[project]
name = "ydpy"
version = "0.1.0"
authors = [
    { name = "ityeri", email = "ityeri9@gmail.com" },
]
description = "Fast, lightweight, simple, with async support and rich-bot-detection-avoidance youtube download library written in python"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICENSE"]
dependencies = [
    "httpx",
    "yarl",
]

[project.optional-dependencies]
test = [
    "pytest>=8.0",
]

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]
pythonpath = ["src"]

[project.urls]
Homepage = "https://github.com/ityeri/ydpy"
Issues = "https://github.com/ityeri/ydpy/issues"

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["ydpy", "ydpy.*"]
exclude = ["tests*", ".*"]
